### ISSUE TITLE
fitbit が OAuth 1.0 をサポートしなくなった

### ISSUE THREAD

**Issue by a-know** [a-know/a-know-home-rails#151]
https://community.fitbit.com/t5/Web-API/OAuth-1-0a-removal-update/m-p/1272107#M5059

```
A*​ `NoMethodError` ​*occurred while*​ `GET </a_know_metricks/steps>` ​*was processed by*​ `activity_metricks#collect_steps`
Exception
----------------
undefined method '[]' for nil:NilClass

Hostname
----------------
a-know-home-web

Backtrace
----------------
```/var/www/a-know-home/releases/20160801091335/lib/fitbit.rb:15:in `todays_steps'
/var/www/a-know-home/releases/20160801091335/app/controllers/activity_metricks_controller.rb:11:in `collect_steps'
/var/www/a-know-home/shared/bundle/ruby/2.3.0/gems/actionpack-5.0.0/lib/action_controller/metal/basic_implicit_render.rb:4:in `send_action'
/var/www/a-know-home/shared/bundle/ruby/2.3.0/gems/actionpack-5.0.0/lib/abstract_controller/base.rb:188:in `process_action'
/var/www/a-know-home/shared/bundle/ruby/2.3.0/gems/actionpack-5.0.0/lib/action_controller/metal/rendering.rb:30:in `process_action'
/var/www/a-know-home/shared/bundle/ruby/2.3.0/gems/actionpack-5.0.0/lib/abstract_controller/callbacks.rb:20:in `block in process_action'
/var/www/a-know-home/shared/bundle/ruby/2.3.0/gems/activesupport-5.0.0/lib/active_support/callbacks.rb:97:in `__run_callbacks__'
/var/www/a-know-home/shared/bundle/ruby/2.3.0/gems/activesupport-5.0.0/lib/active_support/callbacks.rb:750:in `_run_process_action_callbacks'
/var/www/a-know-home/shared/bundle/ruby/2.3.0/gems/activesupport-5.0.0/lib/active_support/callbacks.rb:90:in `run_callbacks'
/var/www/a-know-home/shared/bundle/ruby/2.3.0/gems/actionpack-5.0.0/lib/abstract_controller/callbacks.rb:19:in `process_action'
/var/www/a-know-home/shared/bundle/ruby/2.3.0/gems/actionpack-5.0.0/lib/action_controller/metal/rescue.rb:20:in `process_action'
/var/www/a-know-home/shared/bundle/ruby/2.3.0/gems/actionpack-5.0.0/lib/action_controller/metal/instrumentation.rb:32:in `block in process_action'
/var/www/a-know-home/shared/bundle/ruby/2.3.0/gems/activesupport-5.0.0/lib/active_support/notifications.rb:164:in `block in instrument'
/var/www/a-know-home/shared/bundle/ruby/2.3.0/gems/activesupport-5.0.0/lib/active_support/notifications/instrumenter.rb:21:in `instrument'
/var/www/a-know-home/shared/bundle/ruby/2.3.0/gems/activesupport-5.0.0/lib/active_support/notifications.rb:164:in `instrument'
/var/www/a-know-home/shared/bundle/ruby/2.3.0/gems/actionpack-5.0.0…
```

**Comment by a-know** [comment]
Mackerel の外形監視で API を叩かせていたけど、一旦止めた。

**Comment by a-know** [comment]
いま使ってる gem はまだ OAuth 2 に対応できていないっぽい。
これが使えるかも。https://github.com/gupta-ankit/fitgem_oauth2

**Comment by a-know** [comment]
fitgem はメンテ止まってるっぽい？
fitgem_oauth2、ずいぶんインタフェース変わるし、旨味は少なそう。。

**Comment by a-know** [comment]
どうせ作り変えるんだったら pebble から取るようにしたいかも

**Comment by a-know** [comment]
pebble は pebble で、pebble health というのが絡んでる関係で面倒くさそう。

**Comment by a-know** [comment]
google fit と連携できるのか。。

**Comment by a-know** [comment]
Google fit に集約できると、現状 analytics のデータを取るのにも既に google-api-client-ruby を使ってることもあり、楽にできそう。

いったん pebble と Google fit を連携してみた。
しばらくこれで過ごしてみたあと、 https://developers.google.com/apis-explorer/#p/fitness/v1/ とかから目的のデータが取得できるかどうか試してみる。

**Comment by a-know** [comment]
Google fit はまだサービスアカウントに対応してない。
いったんクローズする。
