### ISSUE TITLE
unicorn 再起動時に Cannot allocate memory エラー

### ISSUE THREAD

**Issue by a-know** [a-know/a-know-home-rails#18]
fork できてない？

```
E, [2016-01-07T09:29:19.462148 #9936] ERROR -- : Cannot allocate memory - fork(2) (Errno::ENOMEM)
/var/www/a-know-home/shared/bundle/ruby/2.3.0/gems/unicorn-5.0.1/lib/unicorn/http_server.rb:503:in `fork'
/var/www/a-know-home/shared/bundle/ruby/2.3.0/gems/unicorn-5.0.1/lib/unicorn/http_server.rb:503:in `spawn_missing_workers'
/var/www/a-know-home/shared/bundle/ruby/2.3.0/gems/unicorn-5.0.1/lib/unicorn/http_server.rb:132:in `start'
/var/www/a-know-home/shared/bundle/ruby/2.3.0/gems/unicorn-5.0.1/bin/unicorn_rails:209:in `<top (required)>'
/var/www/a-know-home/shared/bundle/ruby/2.3.0/bin/unicorn_rails:23:in `load'
/var/www/a-know-home/shared/bundle/ruby/2.3.0/bin/unicorn_rails:23:in `<main>'
E, [2016-01-07T09:29:19.486045 #24843] ERROR -- : reaped #<Process::Status: pid 9936 exit 1> exec()-ed
```

**Comment by a-know** [comment]
[ここらへん](http://stackoverflow.com/questions/21335526/unicorn-restarting-on-its-own-no-memory-gets-killed)、有用なことを言ってそう

**Comment by a-know** [comment]
#19 をやってみたが、解消せず。

他の解決策を探ってみる。

**Comment by a-know** [comment]
micro だと worker プロセス 3 は多すぎるのだろうか。。

```rb
# workers
worker_processes 3
```

**Comment by a-know** [comment]
https://github.com/a-know/a-know-home-server/pull/21 の対応で是正した。
close する
